# Shape Manipulation

# change the shape of an array

In [1]:
import numpy as np
from numpy import *

In [2]:
a = np.floor(10*np.random.random((3,4)))

In [3]:
a

array([[3., 9., 7., 2.],
       [5., 8., 1., 8.],
       [6., 7., 5., 3.]])

In [7]:
a.shape

(3, 4)

**以下三个命令可以改变数组的形状，但是不会改变原来的数组**

In [5]:
a.ravel()   # 返回的是扁平化的数组

array([3., 9., 7., 2., 5., 8., 1., 8., 6., 7., 5., 3.])

In [8]:
a.reshape(6, 2) # 返回修改形状的数组

array([[3., 9.],
       [7., 2.],
       [5., 8.],
       [1., 8.],
       [6., 7.],
       [5., 3.]])

In [9]:
a.T # 返回转置后的数组

array([[3., 5., 6.],
       [9., 8., 7.],
       [7., 1., 5.],
       [2., 8., 3.]])

In [10]:
a.T.shape

(4, 3)

In [11]:
a.shape

(3, 4)

**`resize`在原数组基础上进行修改**

In [12]:
a

array([[3., 9., 7., 2.],
       [5., 8., 1., 8.],
       [6., 7., 5., 3.]])

In [13]:
a.resize((2,6))

In [14]:
a

array([[3., 9., 7., 2., 5., 8.],
       [1., 8., 6., 7., 5., 3.]])

## Stacking together different arrays

In [15]:
a = np.floor(10*np.random.random((2, 2)))

In [16]:
a

array([[5., 9.],
       [0., 4.]])

In [17]:
b = np.floor(10*np.random.random((2, 2)))

In [18]:
b

array([[6., 1.],
       [7., 4.]])

In [19]:
np.vstack((a, b))

array([[5., 9.],
       [0., 4.],
       [6., 1.],
       [7., 4.]])

In [20]:
np.hstack((a,b))

array([[5., 9., 6., 1.],
       [0., 4., 7., 4.]])

In [21]:
np.column_stack((a,b))

array([[5., 9., 6., 1.],
       [0., 4., 7., 4.]])

In [22]:
a = np.array([4., 2.])

In [23]:
b = np.array([3., 8.])

In [24]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [25]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [26]:
a[:,newaxis]

array([[4.],
       [2.]])

In [27]:
np.column_stack((a[:newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [28]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [29]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

## Splitting one array into several smaller ones

In [30]:
a = np.floor(10*np.random.random((2,12)))

In [31]:
a

array([[2., 8., 9., 7., 1., 8., 7., 0., 0., 9., 3., 7.],
       [0., 2., 1., 1., 3., 0., 7., 4., 1., 4., 9., 6.]])

In [32]:
np.hsplit(a,3) # 分为三个数组

[array([[2., 8., 9., 7.],
        [0., 2., 1., 1.]]),
 array([[1., 8., 7., 0.],
        [3., 0., 7., 4.]]),
 array([[0., 9., 3., 7.],
        [1., 4., 9., 6.]])]

In [33]:
np.hsplit(a,(3,4)) # 在第三个和第四个列分割

[array([[2., 8., 9.],
        [0., 2., 1.]]),
 array([[7.],
        [1.]]),
 array([[1., 8., 7., 0., 0., 9., 3., 7.],
        [3., 0., 7., 4., 1., 4., 9., 6.]])]